# Generated by Django 3.1.5 on 2021-06-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='regioncode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='subregion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='subregioncode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
